apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-cameras
  namespace: default
data:
  mock: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "folder": "/datasets",
      "cameras_id": [
          0,
          1,
          2,
          3
      ],
      "videos": [
          {
              "person_id": 1,
              "gesture_id": 6,
              "iterations": 1
          }
      ],
      "loop": true
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "mock-cameras"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mock-cameras
    spec:
      containers:
        - name: "mock-cameras"
          image: luizcarloscf/mock-cameras:0.0.1
          command: ["python3"]
          args: ["/opt/is/src/service.py", "/opt/options/options.json"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
          volumeMounts:
            - mountPath: /opt/options
              name: options
            - mountPath: /datasets
              name: datasets
              readOnly: true
      volumes:
        - name: options
          configMap:
            name: mock-cameras
            items:
              - key: mock
                path: options.json
        - name: datasets
          hostPath:
            path: /public/datasets/ufes-2020-01-23/
            type: Directory
